# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-central-1" # TODO: get this from common.hcl somehow
  default_tags {
    tags = {
      ManagedBy  = "Terraform"
      Application = "WeatherApp"
    }
  }
}
